changelogV2
ManakinCubber/JirHub pull request #49
Opened 2022-06-21 13:32 UTC by ZayedH

2022-06-21 13:48 UTC, rflavien requested changes

2022-06-21 13:48 UTC, rflavien commented on src/Handler/ChangelogHandler.php
> +        $result = $this->commitRepository->getChangelog($prev_head, $head);
ne pas faire 2 fois l'appel là car il est pas performant

2022-06-21 13:48 UTC, rflavien commented on src/Controller/DashboardController.php
> +        //dd($this->handler->getData());
```suggestion
```

2022-06-21 13:48 UTC, rflavien commented on src/Controller/ChangelogController.php
> +        //dd($this->handler);
```suggestion
```

2022-06-21 13:49 UTC, rflavien requested changes

2022-06-21 13:49 UTC, rflavien commented on src/Dashboard/Handler/DashboardHandler.php
> +        //dd($cacheItem);
```suggestion
```

2022-06-22 09:37 UTC, rflavien requested changes

2022-06-22 09:37 UTC, rflavien commented on src/Handler/ChangelogHandler.php
> +            if (gettype($value) == 'array') {
```suggestion
            if (is_array($value)) {
```

2022-06-22 09:37 UTC, rflavien commented on src/Handler/ChangelogHandler.php
> +        return ['num' => count($isString), 'type' => $isString, 'messageLinks' =>  $messagesLinks];
```suggestion
        return ['num' => count($messagesLinks), 'type' => $isString, 'messageLinks' =>  $messagesLinks];
```

2022-06-22 09:37 UTC, rflavien commented on src/Handler/ChangelogHandler.php
> +        $isString = [];
```suggestion
        $types = [];
```

2022-06-22 09:37 UTC, rflavien requested changes

2022-06-22 09:37 UTC, rflavien commented on templates/dashboard/index.html.twig
> +    <a href="/commits" class="button is-normal" style="left: right;margin: 15px">view commits with links</a>
```suggestion
    <a href="/commits" class="button is-normal" style="left: right;margin: 15px">view current changelog</a>
    <a href="/changelog" class="button is-normal" style="float: right;margin: 15px">view current changelog (raw)</a>
```

2022-06-22 11:36 UTC, ZayedH commented on src/Handler/ChangelogHandler.php
> +        $messages = array_filter(array_column($messagesLinks, 'message'), function ($message) {
C bon pour C'est fait

2022-06-22 11:56 UTC, rflavien commented on templates/dashboard/index.html.twig
> +    <a href="/commits" class="button is-normal" style="left: right;margin: 15px">view commits with links</a>
tu peux ajouter `style="display:inline-block"` sur les 2 liens, ça devrait les mettre un en dessous de l'autre

2022-06-22 12:19 UTC, rflavien approved these changes

2022-06-22 12:19 UTC, merged